### ISSUE TITLE
[question] What is your development setup?

### ISSUE THREAD

**Issue by amq** [nikai3d/ce-challenges#1]
What are you using to code in all those languages? How are you debugging?

**Comment by nikai3d** [comment]
> What are you using to code in all those languages?

I'm a Vim user. However, I should add that I'm neither particularly skillful in respect to this editor, nor would I feel the need to use any fancy plugins.
The programming languages I'm using are easy to install on my Linux desktops, which currently run Gentoo and OpenSUSE.

> How are you debugging?

Well, I must admit that to the most part I'm a "print debugger". For small toy programs like these, I never felt the need for anything more sophisticated.
